# Generated by Django 5.0.6 on 2024-05-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_company', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_intitial_salary', models.IntegerField()),
                ('job_final_salary', models.IntegerField()),
                ('job_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
