# Generated by Django 5.0.6 on 2024-05-17 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBAPP', '0005_joblist_job_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_education', models.CharField(max_length=100)),
                ('applicant_experience', models.CharField(max_length=100)),
                ('applicant_internship', models.CharField(max_length=3000)),
                ('applicant_cv', models.FileField(upload_to='')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOBAPP.joblist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JOBAPP.register')),
            ],
        ),
    ]
