# Generated by Django 5.0.6 on 2024-05-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBAPP', '0006_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
