# Generated by Django 5.0.6 on 2024-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBAPP', '0007_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_status',
            field=models.CharField(default='Not Applied', max_length=100, null=True),
        ),
    ]
